-- EXAMPLE 1
SELECT CUSTOMER_NUM,CUSTOMER_NAME,REP.REP_NUM,LAST_NAME,FIRST_NAME
FROM REP JOIN CUSTOMER
ON REP.REP_NUM=CUSTOMER.REP_NUM;

-- EXAMPLE 2
SELECT CUSTOMER_NUM,CUSTOMER_NAME,REP.REP_NUM,LAST_NAME,FIRST_NAME
FROM REP JOIN CUSTOMER
ON REP.REP_NUM = CUSTOMER.REP_NUM
WHERE CREDIT_LIMIT=7500;

-- EXAMPLE 3
SELECT ORDER_NUM,ORDER_LINE.PART_NUM,DESCRIPTION,NUM_ORDERED,QUOTED_PRICE,PRICE
FROM PART JOIN ORDER_LINE
ON PART.PART_NUM=ORDER_LINE.PART_NUM;

-- EXAMPLE 4
SELECT DESCRIPTION 
FROM PART JOIN ORDER_LINE
ON PART.PART_NUM=ORDER_LINE.PART_NUM
WHERE ORDER_NUM='21610';

SELECT DESCRIPTION
FROM PART
WHERE PART_NUM IN
	 (SELECT PART_NUM
	  FROM ORDER_LINE
	  WHERE ORDER_NUM='21610');
	  
-- EXAMPLE 5
SELECT ORDER_NUM,ORDER_DATE
	FROM ORDERS
	WHERE EXISTS
	(SELECT * 
	 FROM ORDER_LINE
	 WHERE ORDERS.ORDER_NUM=ORDER_LINE.ORDER_NUM
	 AND PART_NUM='DR93');	  

-- EXAMPLE 5 USING JOIN	
SELECT ORDERS.ORDER_NUM,ORDER_DATE
FROM ORDERS JOIN ORDER_LINE
ON ORDERS.ORDER_NUM=ORDER_LINE.ORDER_NUM
WHERE PART_NUM = 'DR93';

-- EXAMPLE 6
SELECT ORDER_NUM,ORDER_DATE
FROM ORDERS
WHERE ORDER_NUM IN
	  (SELECT ORDER_NUM
	   FROM ORDER_LINE
	   WHERE PART_NUM IN
			(SELECT PART_NUM
		     FROM PART
		     WHERE WAREHOUSE='3'));

-- EXAMPLE 6 USING JOIN
SELECT ORDERS.ORDER_NUM,ORDER_DATE
FROM ORDERS JOIN ORDER_LINE
ON ORDERS.ORDER_NUM=ORDER_LINE.ORDER_NUM
JOIN PART 
ON ORDER_LINE.PART_NUM=PART.PART_NUM
WHERE WAREHOUSE='3';  

-- EXAMPLE 7
SELECT CUSTOMER_NUM,ORDERS.ORDER_NUM,ORDER_DATE,
SUM(NUM_ORDERED*QUOTED_PRICE) AS ORDER_TOTAL
	FROM ORDERS JOIN ORDER_LINE
	ON ORDERS.ORDER_NUM=ORDER_LINE.ORDER_NUM
	GROUP BY ORDERS.ORDER_NUM,CUSTOMER_NUM,ORDER_DATE
	HAVING SUM(NUM_ORDERED*QUOTED_PRICE)>1000
	ORDER BY ORDERS.ORDER_NUM;
	
-- EXAMPLE 8
SELECT R.REP_NUM,LAST_NAME,FIRST_NAME,C.CUSTOMER_NUM,CUSTOMER_NAME
FROM REP R JOIN CUSTOMER C
ON R.REP_NUM=C.REP_NUM;	 

-- EXAMPLE 9
SELECT F.CUSTOMER_NUM,F.CUSTOMER_NAME,S.CUSTOMER_NUM,S.CUSTOMER_NAME,F.BALANCE
FROM CUSTOMER F JOIN CUSTOMER S
ON F.CITY=S.CITY
WHERE F.CUSTOMER_NUM<S.CUSTOMER_NUM
ORDER BY F.CUSTOMER_NUM,S.CUSTOMER_NUM;

-- EXAMPLE 10
SELECT PART_NUM,NUM_ORDERED,OL.ORDER_NUM,ORDER_DATE,
C.CUSTOMER_NUM,CUSTOMER_NAME,LAST_NAME
	FROM REP R JOIN CUSTOMER C
	ON R.REP_NUM=C.REP_NUM
	JOIN ORDERS O
	ON C.CUSTOMER_NUM=O.CUSTOMER_NUM
	JOIN ORDER_LINE OL
	ON O.ORDER_NUM=OL.ORDER_NUM;

-- EXAMPLE 11
SELECT CUSTOMER_NUM,CUSTOMER_NAME
FROM CUSTOMER C
WHERE REP_NUM='65'
UNION
SELECT C.CUSTOMER_NUM,CUSTOMER_NAME
FROM CUSTOMER C JOIN ORDERS O
ON C.CUSTOMER_NUM = O.CUSTOMER_NUM;

-- EXAMPLE 11 UNION ALL
SELECT CUSTOMER_NUM,CUSTOMER_NAME
FROM CUSTOMER C
WHERE REP_NUM='65'
UNION ALL
SELECT C.CUSTOMER_NUM,CUSTOMER_NAME
FROM CUSTOMER C JOIN ORDERS O
ON C.CUSTOMER_NUM = O.CUSTOMER_NUM;

-- EXAMPLE 11 INTERSECT
SELECT CUSTOMER_NUM,CUSTOMER_NAME
FROM CUSTOMER C
WHERE REP_NUM='65'
INTERSECT
SELECT C.CUSTOMER_NUM,CUSTOMER_NAME
FROM CUSTOMER C JOIN ORDERS O
ON C.CUSTOMER_NUM = O.CUSTOMER_NUM;	 	      	 	 

-- EXAMPLE 11 EXCEPT
SELECT CUSTOMER_NUM,CUSTOMER_NAME
FROM CUSTOMER C
WHERE REP_NUM='65'
EXCEPT
SELECT C.CUSTOMER_NUM,CUSTOMER_NAME
FROM CUSTOMER C JOIN ORDERS O
ON C.CUSTOMER_NUM = O.CUSTOMER_NUM;	 

SELECT C.CUSTOMER_NUM,CUSTOMER_NAME
FROM CUSTOMER C JOIN ORDERS O
ON C.CUSTOMER_NUM = O.CUSTOMER_NUM	 
EXCEPT
SELECT CUSTOMER_NUM,CUSTOMER_NAME
FROM CUSTOMER C
WHERE REP_NUM='65'

--EXAMPLE 12
SELECT CUSTOMER_NUM,CUSTOMER_NAME,BALANCE, REP_NUM
FROM CUSTOMER
WHERE BALANCE > ALL
	(SELECT BALANCE
	FROM CUSTOMER
	WHERE REP_NUM='65');
	
SELECT CUSTOMER_NUM,CUSTOMER_NAME,BALANCE, REP_NUM
FROM CUSTOMER
WHERE BALANCE > 
	(SELECT MAX(BALANCE)
	FROM CUSTOMER
	WHERE REP_NUM='65');

-- EXAMPLE 13
SELECT CUSTOMER_NUM,CUSTOMER_NAME,BALANCE, REP_NUM
FROM CUSTOMER
WHERE BALANCE > ANY
	(SELECT BALANCE
	FROM CUSTOMER
	WHERE REP_NUM='65');
	
SELECT CUSTOMER_NUM,CUSTOMER_NAME,BALANCE, REP_NUM
FROM CUSTOMER
WHERE BALANCE > 
	(SELECT MIN(BALANCE)
	FROM CUSTOMER
	WHERE REP_NUM='65');
	
-- EXAMPLE 15
SELECT C.CUSTOMER_NUM,CUSTOMER_NAME,ORDER_NUM,ORDER_DATE
FROM CUSTOMER C
LEFT JOIN ORDERS O
ON C.CUSTOMER_NUM=O.CUSTOMER_NUM
ORDER BY C.CUSTOMER_NUM;	

SELECT C.CUSTOMER_NUM,CUSTOMER_NAME,ORDER_NUM,ORDER_DATE
FROM ORDERS O
RIGHT JOIN CUSTOMER C
ON C.CUSTOMER_NUM=O.CUSTOMER_NUM
ORDER BY C.CUSTOMER_NUM;

SELECT C.CUSTOMER_NUM,CUSTOMER_NAME,ORDER_NUM,ORDER_DATE
FROM ORDERS O
FULL JOIN CUSTOMER C
ON C.CUSTOMER_NUM=O.CUSTOMER_NUM
ORDER BY C.CUSTOMER_NUM;

-- EXAMPLE 16
SELECT C.CUSTOMER_NUM,CUSTOMER_NAME,ORDER_NUM,ORDER_DATE
FROM CUSTOMER C, ORDERS O;

