-- Exercise 1

SELECT PART_NUM, DESCRIPTION 
FROM PART;

-- Exercise 2

SELECT *
FROM REP;

-- Exercise 3

SELECT CUSTOMER_NAME
FROM CUSTOMER
WHERE CREDIT_LIMIT >=10000;

-- Exercise 4

SET DATEFORMAT dmy
SELECT ORDER_NUM
FROM ORDER
WHERE CUSTOMER_NUM='148' AND ORDER_DATE='23/10/2003';

-- Exercise 5

SELECT CUSTOMER_NUM,CUSTOMER_NAME
FROM REP
WHERE REP_NUM='20' OR REP_NUM='65';

-- Exercise 6

SELECT PART_NUM,DESCRIPTION
FROM PART
WHERE NOT (CLASS='HW');

-- Exercise 7

SELECT PART_NUM,DESCRIPTION,ON_HAND
FROM PART
WHERE ON_HAND BETWEEN 10 AND 25;

SELECT PART_NUM,DESCRIPTION,ON_HAND
FROM PART
WHERE ON_HAND >= 10 AND ON_HAND<=25;

-- Exercise 8

SELECT PART_NUM,DESCRIPTION,(ON_HAND*PRICE) AS ON_HAND_VALUE
FROM PART
WHERE CLASS='AP';

-- Exercise 9

SELECT PART_NUM,DESCRIPTION,(ON_HAND*PRICE) AS ON_HAND_VALUE
FROM PART
WHERE (ON_HAND*PRICE >=7500);

-- Exercise 10

SELECT PART_NUM,DESCRIPTION, (ON_HAND*PRICE)
FROM PART
WHERE CLASS IN ('HW','SG');

-- Exercise 11

SELECT CUSTOMER_NUM,CUSTOMER_NAME
FROM CUSTOMER
WHERE CUSTOMER_NAME LIKE 'D%';

-- Exercise 12

SELECT * 
FROM PART
ORDER BY DESCRIPTION;

-- Exercise 13

SELECT * 
FROM PART
ORDER BY CLASS,PART_NUM;

-- Exercise 14

SELECT COUNT(CUSTOMER_NUM)
FROM CUSTOMER
WHERE BALANCE < CREDIT_LIMIT;

-- Exercise 15

SELECT SUM(BALANCE)
FROM CUSTOMER
WHERE REP='65' AND BALANCE < CREDIT_LIMIT;

-- Exercise 16

SELECT PART_NUM, DESCRIPTION, (ON_HAND*PRICE)
FROM PART
WHERE ON_HAND > 
		(SELECT AVG(ON_HAND)
		FROM PART);
		
-- Exercise 17

SELECT MIN(PRICE)
FROM PART;

-- Exercise 18

SELECT PART_NUM,DESCRIPTION,PRICE
FROM PART
WHERE PRICE = 
			(SELECT MAX(PRICE)
			FROM PART);
			
-- Exercise 19

SELECT REP_NUM,SUM(BALANCE)
FROM REP
GROUP BY REP_NUM
ORDER BY REP_NUM;

-- Exercise 20

SELECT REP_NUM,SUM(BALANCE)
FROM REP
GROUP BY REP_NUM
HAVING SUM(BALANCE)> 10000;

-- Exercise 21

SELECT PART_NUM
FROM PART
WHERE DESCRIPTION IS NULL;


			
			