-- EXAMPLE 1
SELECT CUSTOMER_NUM,CUSTOMER_NAME,BALANCE
FROM CUSTOMER;

-- EXAMPLE 2
SELECT *
FROM PART;

-- EXAMPLE 3
SELECT CUSTOMER_NAME
FROM CUSTOMER
WHERE CUSTOMER_NUM='148';

-- EXAMPLE 4
SELECT CUSTOMER_NUM,CUSTOMER_NAME
FROM CUSTOMER
WHERE CITY='Grove';

-- EXAMPLE 5
SELECT CUSTOMER_NUM,CUSTOMER_NAME,BALANCE,CREDIT_LIMIT
FROM CUSTOMER
WHERE BALANCE>CREDIT_LIMIT;

-- EXAMPLE 6
SELECT DESCRIPTION
FROM PART
WHERE (WAREHOUSE='3')
AND (ON_HAND>25);

-- EXAMPLE 7
SELECT DESCRIPTION
FROM PART
WHERE (WAREHOUSE='3')
OR (ON_HAND>25);

-- EXAMPLE 8
SELECT DESCRIPTION
FROM PART
WHERE(WAREHOUSE<>'3');

-- EXAMPLE 9
SELECT CUSTOMER_NUM,CUSTOMER_NAME,BALANCE
FROM CUSTOMER
WHERE BALANCE BETWEEN 2000 AND 5000;

--SELECT CUSTOMER_NUM,CUSTOMER_NAME,BALANCE
--FROM CUSTOMER
--WHERE BALANCE >= 2000 AND BALANCE <=5000;

-- EXAMPLE 10
SELECT CUSTOMER_NUM,CUSTOMER_NAME,(CREDIT_LIMIT-BALANCE) AS AVAILABLE_CREDIT
FROM CUSTOMER;

-- EXAMPLE 11
SELECT CUSTOMER_NUM,CUSTOMER_NAME,(CREDIT_LIMIT-BALANCE)AS AVAILABLE_CREDIT
FROM CUSTOMER
WHERE (CREDIT_LIMIT-BALANCE)>=5000;

-- EXAMPLE 12
SELECT CUSTOMER_NUM,CUSTOMER_NAME,STREET,CITY,STATE,ZIP
FROM CUSTOMER
WHERE STREET LIKE '%Central%';

-- EXAMPLE 13
SELECT CUSTOMER_NUM,CUSTOMER_NAME,CREDIT_LIMIT
FROM CUSTOMER
WHERE CREDIT_LIMIT IN (5000,10000,15000);

-- EXAMPLE 14
SELECT CUSTOMER_NUM,CUSTOMER_NAME,BALANCE
FROM CUSTOMER
ORDER BY BALANCE DESC;

-- EXAMPLE 15
SELECT CUSTOMER_NUM,CUSTOMER_NAME,CREDIT_LIMIT
FROM CUSTOMER
ORDER BY CREDIT_LIMIT DESC, CUSTOMER_NAME;

-- EXAMPLE 16
SELECT COUNT(*)
FROM PART
WHERE CLASS='HW';

--SELECT COUNT(PART_NUM)
--FROM PART
--WHERE CLASS='HW';

-- EXAMPLE 17
SELECT COUNT(*),SUM(BALANCE)
FROM CUSTOMER;

SELECT SUM(BALANCE) AS SUM, AVG(BALANCE) AS AVERAGE, MAX(BALANCE) AS MAX, MIN(BALANCE) AS MIN
FROM CUSTOMER;

-- EXAMPLE 18
SELECT CUSTOMER_NUM
FROM ORDERS;

-- EXAMPLE 19
SELECT DISTINCT CUSTOMER_NUM
FROM ORDERS;

-- EXAMPLE 20
SELECT COUNT(DISTINCT(CUSTOMER_NUM))
FROM ORDERS;

-- EXAMPLE 21
SELECT PART_NUM
FROM PART
WHERE CLASS='AP';

SELECT ORDER_NUM
FROM ORDER_LINE
WHERE PART_NUM IN ('CD52','DR93','DW11','KL62','KT03');

-- EXAMPLE 22
SELECT ORDER_NUM
FROM ORDER_LINE
WHERE PART_NUM IN
		(SELECT PART_NUM
		 FROM PART
		 WHERE CLASS='AP');
		 
-- EXAMPLE 23
SELECT CUSTOMER_NUM,CUSTOMER_NAME,BALANCE
FROM CUSTOMER
WHERE BALANCE >
		(SELECT AVG(BALANCE)
		 FROM CUSTOMER);
	
-- EXAMPLE 24
SELECT REP_NUM,AVG(BALANCE) AS AVERAGE_BALANCE
FROM CUSTOMER
GROUP BY REP_NUM
ORDER BY REP_NUM;

-- EXAMPLE 25
SELECT REP_NUM,AVG(BALANCE) AS AVERAGE_BALANCE
FROM CUSTOMER
GROUP BY REP_NUM
HAVING COUNT(*)<4
ORDER BY REP_NUM;
		 
-- EXAMPLE 26
SELECT CREDIT_LIMIT,COUNT(*) AS CUSTOMER_COUNT
FROM CUSTOMER
GROUP BY CREDIT_LIMIT;

-- EXAMPLE 27
SELECT CREDIT_LIMIT,COUNT(*) AS CUSTOMER_COUNT
FROM CUSTOMER
GROUP BY CREDIT_LIMIT
HAVING COUNT(*)>1;

-- EXAMPLE 28
SELECT CREDIT_LIMIT,COUNT(*) AS CUSTOMER_COUNT
FROM CUSTOMER
WHERE REP_NUM='20'
GROUP BY CREDIT_LIMIT;

-- EXAMPLE 29
SELECT CREDIT_LIMIT,COUNT(*)AS CUSTOMER_COUNT 
FROM CUSTOMER
WHERE REP_NUM='20'
GROUP BY CREDIT_LIMIT
HAVING COUNT(*)>1;

-- EXAMPLE 30
SELECT CUSTOMER_NUM,CUSTOMER_NAME
FROM CUSTOMER
WHERE STREET IS NULL;
