--Updating Database

-- Example 1
CREATE TABLE LEVEL1_CUSTOMER
	(CUSTOMER_NUM CHAR(3) PRIMARY KEY,
	CUSTOMER_NAME CHAR(35),
	BALANCE DECIMAL(8,2),
	CREDIT_LIMIT DECIMAL(8,2),
	REP_NUM CHAR(2))

-- Example 2	
INSERT INTO LEVEL1_CUSTOMER
	SELECT CUSTOMER_NUM,CUSTOMER_NAME,BALANCE,
	CREDIT_LIMIT,REP_NUM
	FROM CUSTOMER 
	WHERE CREDIT_LIMIT=7500 
	
-- SELECT * from LEVEL1_CUSTOMER	

-- Example 3
UPDATE LEVEL1_CUSTOMER
	SET CUSTOMER_NAME='Ann''s store'
	WHERE CUSTOMER_NUM = '148';
	
-- Example 4
UPDATE LEVEL1_CUSTOMER
	SET CREDIT_LIMIT=8000
	WHERE CREDIT_LIMIT=7500
	AND BALANCE < CREDIT_LIMIT
	
-- Example 5
INSERT INTO LEVEL1_CUSTOMER
	VALUES
	('895','Peter and Margaret''s',0,8000,'20')	
		